exports.getAllUser = async (req, res) => {
  try {
  } catch (error) {
    res.status(401).json({ message: 'Something went Wrong!' });
  }
};
